CREATE USER TENX
  IDENTIFIED BY letmein12
  DEFAULT TABLESPACE ILIMWEB
  TEMPORARY TABLESPACE TEMP
  PROFILE EIS_APPLICATION_ACCOUNT
  ACCOUNT UNLOCK;
  -- 4 Roles for TENX 
  GRANT CTM_USER TO TENX;
  GRANT DBA TO TENX;
  GRANT ORMTOOLS TO TENX WITH ADMIN OPTION;
  GRANT PDF_USER TO TENX;
  ALTER USER TENX DEFAULT ROLE ALL;
  -- 15 System Privileges for TENX 
  GRANT ALTER ANY TRIGGER TO TENX;
  GRANT ANALYZE ANY TO TENX;
  GRANT CREATE ANY INDEX TO TENX;
  GRANT CREATE ANY TABLE TO TENX;
  GRANT CREATE ANY TYPE TO TENX;
  GRANT CREATE DATABASE LINK TO TENX;
  GRANT CREATE PROCEDURE TO TENX;
  GRANT CREATE PUBLIC SYNONYM TO TENX;
  GRANT CREATE SESSION TO TENX;
  GRANT CREATE TABLE TO TENX;
  GRANT CREATE TRIGGER TO TENX;
  GRANT DROP ANY INDEX TO TENX;
  GRANT DROP ANY TABLE TO TENX;
  GRANT DROP PUBLIC SYNONYM TO TENX;
  GRANT UNLIMITED TABLESPACE TO TENX;